title: Stackbit Starter Theme
baseurl: /
permalink: '/:title/'
collections:
  posts:
    permalink: '/posts/:title/'
description: An ultra customizable generic theme for Stackbit
header:
  title: Wedding's by Sarah
  has_nav: true
  nav_links:
    - label: Contact Us
      url: /contact
      style: primary
footer:
  has_nav: true
  nav_links:
    - label: Contact Us
      url: /contact
      style: link
    - label: Privacy and Terms
      url: /terms
      style: link
  has_social: true
  social_links: []
  content: '&copy; Stackbit-Starter. All rights reserved.'
  links:
    - label: Made with Stackbit.
      url: 'https://www.stackbit.com'
      style: link
      new_window: true
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-menus
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - README.md
  - netlify.toml
  - stackbit-build.sh
  - stackbit-pull.js
